---
name: Check Markdown links

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: lycheeverse/lychee-action@v2.9.0
        with:
          args: --verbose --no-progress './**/*.md'
